### ISSUE TITLE
Issues with updated open source version

### ISSUE THREAD

**Issue by Alex10** [SiliconLabs/thunderboard-android#13]
Hello Silicon lab team,

I don’t understand no one has a working version?

I downloaded the again newest version and we still have the same issues as before.

The applications come with apk file. The existing apk file works but why compiled by myself is crashed all the time?
Can somebody help me with this version?

Thank you,
Alex

**Comment by silabs-tiago** [comment]
Hi @Alex10,

Please check the latest commit, the issue has been fixed.

The problem was that we temporarily removed the cloud streaming functionality but the app still required the firebase configuration file, otherwise it crashed as you were observing.

When we bring back the cloud functionality this configuration file will again be necessary but then we will provide instructions on the readme file.

Regards,
Tiago

**Comment by Alex10** [comment]
Hello Tiago,
Thank you for the update.
At this moment, I don't need the cloud interface.
Best,
Alex
